language: c
git:
  depth: false
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  tag_name: "v0.1.$(git rev-list --no-merges --count HEAD master)-alpha"
  name: "v0.1.$(git rev-list --no-merges --count HEAD master)-alpha"
  file: "gmx-amxx.zip"
  skip_cleanup: true
  on:
    tags: false
    branch: master
script: bash deploy.sh